services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: bentopdf
    ports:
      - '8092:8080'
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
