services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_STOPPED: false
      WATCHTOWER_SCHEDULE: "0 0 15 * * *"
      DOCKER_API_VERSION: "1.45"
    volumes:
      # Allow Watchtower to access the Docker daemon to update containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab
networks:
  homelab:
    external: true
