services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    restart: unless-stopped
    ports:
      - 8232:8090
    volumes:
      # Persist Beszel application data and configuration on the host
      - ./data:/beszel_data
    networks:
      - homelab

networks:
  homelab:
    external: true
